// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lubhskftgevcgfkzxozx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1Ymhza2Z0Z2V2Y2dma3p4b3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc2MTcwMDcsImV4cCI6MjA4MzE5MzAwN30.g2xNWS50WyInCcSyWjGKec9eVnSJoQO8PZLhK0uO_9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);